### ISSUE TITLE
Is not a menu file obsolete?

### ISSUE THREAD

**Issue by ksharindam** [ImageProcessing-ElectronicPublications/photoquick#10]
now most desktop environment use desktop file to show menu item in their menu.
so is not the menu file desktop/menu/photoquick obsolete?
I think keeping only desktop file is sufficient.

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

:information_source: Tiled WMs are widespread (almost the same as KDE). They use "menu", not "desktop".

PS: I use "menu" (IceWM).
