### ISSUE TITLE
Icons?

### ISSUE THREAD

**Issue by zvezdochiot** [ImageProcessing-ElectronicPublications/photoquick#11]
Hi @ksharindam .

:question: Maybe optimize icons?
```sh
photoquick/src/images$ cat * | wc -c
57208

photoquick$ bash-optimg-all
...

photoquick/src/images$ cat * | wc -c
50335
```

**Comment by zvezdochiot** [comment]
:question: Or is it too early?

**Comment by ksharindam** [comment]
I will check If this does not change color of the icons, then upload optimized version.
but after I finish the plugin implementation.

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

Good. That is the question. Git works very poorly with binary files, so replace them rarely.

**Comment by zvezdochiot** [comment]
no actual.
