### ISSUE TITLE
Photoquick plugins git?

### ISSUE THREAD

**Issue by zvezdochiot** [ImageProcessing-ElectronicPublications/photoquick#12]
:question: Maybe it is worth moving and copy:
```
src/canvas.h
src/plugin.h
plugins/*
```
in new git? Example: `photoquick-plugins`.

**Comment by ksharindam** [comment]
Dont move these three sample plugins.
You can copy them.

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

:question: Why not move? Why are they needed in the main project? Need only a link to them in the documentation, or not?

**Comment by ksharindam** [comment]
Ok, then move them

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

No no no. You are an author. If you do not like it, then you will cease to support the project. Such decisions can only come from you. I can only advise. Just the logic of creating plugins is incomplete if there is no goal to separate the plugins from the viewer.

**Comment by ksharindam** [comment]
I was keeping the plugins just as a part of documentation. Plugin
documention must be in the main repository. And the documentation needs
examples (well commented).

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

It seems that your idea is incompatible with the idea of separation (although for me a link to the new git in the documentation would be enough). I was just hoping for a centralized git with all the plugins. It is a pity that this is incompatible with your idea.
