### ISSUE TITLE
Load Plugin?

### ISSUE THREAD

**Issue by zvezdochiot** [ImageProcessing-ElectronicPublications/photoquick#13]
In release https://github.com/ImageProcessing-ElectronicPublications/photoquick/releases/tag/4.3.0 :
```sh
photoquick-4.3.0/src/bin$ ./photoquick
"/home/zvezdochiot/.local/share/photoquick/plugins" 
Loading : "libbimodal_thresh.so" 
Loading : "libgreyworld.so" 
Loading : "libinvert.so" 
Loading : "libkuwahara.so" 
```
and plugin items are located on the menu.

In current:
```sh
photoquick-t/src/bin$ ./photoquick
"/home/zvezdochiot/.local/share/photoquick/plugins" 
Loading : "libbimodal_thresh.so" 
Loading : "libgreyworld.so" 
Loading : "libinvert.so" 
Loading : "libkuwahara.so" 
```
:bug: But there are no plugins on the menu!

**Comment by ksharindam** [comment]
Did you change the menu path from Filter/Color/.. to Filters/Color/..
Because, i renamed the Filter menu to Filters. So prev plugins need to
update.

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

Got it. Immediately did not pay attention.
