### ISSUE TITLE
shortcut key for Reload "R" is unconventional

### ISSUE THREAD

**Issue by ksharindam** [ImageProcessing-ElectronicPublications/photoquick#14]
Most file managers and other many apps use F5 for refresh. 
I think using F5 is more conventional instead of R.

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

For the first time I hear about F5.

**Comment by ksharindam** [comment]
I use it often in file managers.

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

```sh
$ man feh
...
KEYS
...
     r [reload_image]
             Reload current image.  Useful for webcams
...
```
I'm `r` more familiar.

**Comment by ksharindam** [comment]
Does not matter, because I rarely use reload in this image viewer.
