### ISSUE TITLE
Threshold -> Export to PDF -> segment fault

### ISSUE THREAD

**Issue by zvezdochiot** [ImageProcessing-ElectronicPublications/photoquick#16]
Hi @ksharindam .

New bug.

(`Threshold` or `GrayScale->Threshold Bimod (2, 0)`) -> `Export to PDF` -> `segment fault`

`Threshold BG Scale (8, 0)` -> `Export to PDF` -> :+1:

**Comment by ksharindam** [comment]
it is working fine in my system.

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

Hmm. I'll try `gdb`.

```gdb
(gdb) r
Starting program: /home/zvezdochiot/WORK/soft/git/ImageProcessing-ElectronicPublications/photoquick-tt/src/photoquick 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/i686/cmov/libthread_db.so.1".
[New Thread 0xb4a53b70 (LWP 10562)]
[New Thread 0xb40ffb70 (LWP 10563)]
[Thread 0xb4a53b70 (LWP 10562) exited]
[Thread 0xb40ffb70 (LWP 10563) exited]
[New Thread 0xb40ffb70 (LWP 10568)]
[New Thread 0xb4a53b70 (LWP 10569)]
[New Thread 0xb2fd8b70 (LWP 10570)]

Program received signal SIGSEGV, Segmentation fault.
getPngIdat (rawdata=0x83e4600 "\211PNG\r\n\032\n", rawdata_size=50040) at pdfwriter.cpp:200
200	        read32(size, data); // chunk size
(gdb) 
```

PS: `photoquick.pro`:
```qmake
...
QMAKE_CXXFLAGS = -g -fopenmp -std=c++11
QMAKE_LFLAGS +=
...
```

**Comment by ksharindam** [comment]
maybe a bug for all monochrome image.
even Threshold->Export to PDF may rise this issue.

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

`Threshold BG Scale` does not cause a problem, see https://github.com/ImageProcessing-ElectronicPublications/photoquick/issues/16#issue-651003286 .

**Comment by ksharindam** [comment]
getPngIdat() can cause segfault only if the png data is incomplete or invalid

**Comment by ksharindam** [comment]
You have changed some code. compile the code from current repository without any modifications and then check if segfault occurs.

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

Current:
```gdb
(gdb) r
Starting program: /home/zvezdochiot/WORK/soft/git/ImageProcessing-ElectronicPublications/photoquick-t3/src/photoquick 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/i686/cmov/libthread_db.so.1".
[New Thread 0xb4a53b70 (LWP 428)]
[New Thread 0xb40ffb70 (LWP 429)]
[Thread 0xb4a53b70 (LWP 428) exited]
[Thread 0xb40ffb70 (LWP 429) exited]
[New Thread 0xb40ffb70 (LWP 445)]
[New Thread 0xb4a53b70 (LWP 446)]
[New Thread 0xb2fd8b70 (LWP 447)]

Program received signal SIGSEGV, Segmentation fault.
getPngIdat (rawdata=0x83f6d88 "\211PNG\r\n\032\n", rawdata_size=50040) at pdfwriter.cpp:198
198	        read32(size, data); // chunk size
(gdb) 
```

**Comment by ksharindam** [comment]
The main problem is that i can not reproduce this bug. So it is difficult
to track.

**Comment by zvezdochiot** [comment]
Ok. Maybe the original image will help:

![page0001](https://user-images.githubusercontent.com/12370082/86531936-506bbd80-bece-11ea-847b-e0d877373cfd.jpg)

`Threshold` -> `Export to PDF` -> `segment fault`

**Comment by ksharindam** [comment]
Put some qDebug() in the getPngDat and see at which position of data it is
trying to read before segfault.

**Comment by ksharindam** [comment]
Only this image, some specific images or any image in your system?

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

Gdb clearly says that segfault happens on line 198:
https://github.com/ImageProcessing-ElectronicPublications/photoquick/blob/550b518d93321ee0ab01d0435639377156b50253/src/pdfwriter.cpp#L198

**Comment by ksharindam** [comment]
Yes, but does using any image cause the segfault, or that specific image?

**Comment by zvezdochiot** [comment]
Hmm. So far, only on this.

**Comment by ksharindam** [comment]
Ok

**Comment by ksharindam** [comment]
I have downloaded that image and applied...
Threshold -> Export to PDF
GrayScale -> Bimodal Threshold -> Export to PDF
Threshold -> Bimodal Threshold -> Export to PDF
But segfault did not happen. Here is the pdf output.
[86531936-506bbd80-bece-11ea-847b-e0d877373cfd.pdf](https://github.com/ImageProcessing-ElectronicPublications/photoquick/files/4874897/86531936-506bbd80-bece-11ea-847b-e0d877373cfd.pdf)

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

:ballot_box_with_check: Hmm. So I have `Thread` naughty. To know the problem is purely my system.
