### ISSUE TITLE
Crop?

### ISSUE THREAD

**Issue by zvezdochiot** [ImageProcessing-ElectronicPublications/photoquick#17]
:question: Maybe add "Extend" or "Expand"?

**Comment by ksharindam** [comment]
Extend or expand what?

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

Extend or expand image. Not resize, add margins.

**Comment by ksharindam** [comment]
A plugin can be added easily

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

Not. Main functionality: Crop - Expand.

PS: In GIMP, this is "Canvas Size".

**Comment by ksharindam** [comment]
Crop and expand are completely opposite functions

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

On "No" and no court. I will be using GIMP.
