### ISSUE TITLE
Work Box?

### ISSUE THREAD

**Issue by zvezdochiot** [ImageProcessing-ElectronicPublications/photoquick#18]
Hi @ksharindam .

It is desirable to have a "Work Box" tool. The meaning of the tool is to works only a part of the image with any means of photoquick, after which the result is embedded in the original image and returned to it.

**Comment by ksharindam** [comment]
Something like using rectangular mask, and use all other tools and filters within that mask?
How to determine when to embed that part in original image?

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

Not. The original image is hidden. Only the site remains. A back button should be added.

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

Not. The original image is hidden. Only the site remains. A back button should be added.

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

Not. The original image is hidden. Only the  work box remains (QImage box, x0, y0, widthbox, heightbox). A back button should be added.

❓ Or do you think it is better to make a separate tool: "Mask" (made of rectangles), and integrate it into all the others using the "Off/Mask/Demask" switch? (isn't it overcomplicated?)

**Comment by zvezdochiot** [comment]
See #30
