### ISSUE TITLE
Transform: simple?

### ISSUE THREAD

**Issue by zvezdochiot** [ImageProcessing-ElectronicPublications/photoquick#2]
Hi @ksharindam and all.

:question: Maybe it's worth adding simple shear methods to the transformation?

Sample:

![see](https://svgshare.com/i/Km1.svg)

See also https://github.com/4lex4/scantailor-advanced/issues/119

**Comment by ksharindam** [comment]
This is somewhat similar to perspective transform. but in this case we have to keep height same.
we have to copy paste the code from perspective transform , and change few lines.

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

:warning: Not quite a perspective transform. It is much simpler and assumes symmetry. What is missing from perspective transform.

**Comment by ksharindam** [comment]
yes , it is much simpler. And we can use most of the code from perspective transform for creating the GUI .

**Comment by zvezdochiot** [comment]
:warning: Yes. The only thing is that I get along badly with OOP (you probably already noticed). If I get in directly, then I will “spoil” the logic of the code.

**Comment by zvezdochiot** [comment]
See https://github.com/ImageProcessing-ElectronicPublications/photoquick/issues/9
