### ISSUE TITLE
Resize?

### ISSUE THREAD

**Issue by zvezdochiot** [ImageProcessing-ElectronicPublications/photoquick#21]
Maybe?:
```
[Width]  [Height]  [Ratio]

Ratio = sqrt((Wnew * Hnew) / (W * H)) 
```
Not?

**Comment by ksharindam** [comment]
I dont understand. Please explain

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

If you enter `Width` and `Height`, then `Ratio = sqrt((Wnew * Hnew) / (W * H)) `.  
If you enter `Ratio`, then `Wnew = Ratio * W` and `Hnew = Ratio * H`.  
Default: `Wnew = W`, `Hnew = H` and `Ratio = 1.0 `.
