### ISSUE TITLE
About?

### ISSUE THREAD

**Issue by zvezdochiot** [ImageProcessing-ElectronicPublications/photoquick#22]
Hi @ksharindam .

"About" is optional, but its absence from the "File" menu does not paint the program. A short description is desirable and a link for feedback is just needed. The link is in the documentation, but not in the viewer itself.

**Comment by ksharindam** [comment]
there are hardly two or three users of this program at this time. So currently implementing this is not needed.
But there is a plan in future, to merge Decorate Btn and Tools Btn into one Tools Btn. And Create a new button 'More'. which will contain About , exif data, histogram etc. and some other options.

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

That is, the design is not completed right now? And the secondary points will get in the way for redoing it? Got it.
