### ISSUE TITLE
Photoquick git sample?

### ISSUE THREAD

**Issue by zvezdochiot** [ImageProcessing-ElectronicPublications/photoquick#23]
❓ Maybe you should add a separate git, in which to put example images and their processing? And when git-history becomes too heavy, such git can be removed and rerun.

**Comment by ksharindam** [comment]
Yes, it is a good idea. Create a git repo.

**Comment by zvezdochiot** [comment]
Good. I'll do this from Monday. I'll leave the issue as a reminder for now.

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

See https://github.com/ImageProcessing-ElectronicPublications/photoquick-examples .

How to add a link to the documentation - close this issue.

**Comment by zvezdochiot** [comment]
Complete.
