### ISSUE TITLE
Alpha in reFilter?

### ISSUE THREAD

**Issue by zvezdochiot** [ImageProcessing-ElectronicPublications/photoquick#26]
https://github.com/ImageProcessing-ElectronicPublications/photoquick/blob/cf0b658f73069a8e6436b64b2946490509faebd4/src/main.cpp#L546

I used RGB in this function,
https://github.com/ImageProcessing-ElectronicPublications/photoquick/blob/cf0b658f73069a8e6436b64b2946490509faebd4/src/main.cpp#L557-L558
thinking that the Alpha channel, if present, will remain untouched. But this is not the case. 

Default resize (x4):  
![x4](https://i114.fastpic.ru/big/2021/0313/bb/7e38d3d0026c9bcd11cf4ad9ab7b8abb.png)  
Enable RIS (x4):  
![x4-RIS](https://i114.fastpic.ru/big/2021/0313/f3/73571b848073b49b807d621bf88677f3.png)  

Can you get around this so as not to run into a segfault?
  
PS: **If successful, I intend to use reFilter in Smooth/Blur as an option for unSharp/reBlur.**

**Comment by ksharindam** [comment]
The code seems ok. When it is causing segfault.

**Comment by zvezdochiot** [comment]
@ksharindam say:
>When it is causing segfault.

I'm just not used to QImage yet. I don't understand him well. In c, such a mismatch would inevitably lead to a segfault. Did some experiments on copying qAlpha from source images, but something strange is happening on the test image: 

![RGBA](https://raw.githubusercontent.com/ImageProcessing-ElectronicPublications/photoquick-examples/main/orig/wallwatter.png)  
(https://github.com/ImageProcessing-ElectronicPublications/photoquick-examples/blob/main/orig/wallwatter.png)

I'm clearly missing something. But the result I get is bad. Perhaps a fresh eyes (yours) will solve this problem.
```cpp
                //rowre[x] = qRgb(r, g, b);
                rowre[x] = qRgba(r, g, b, qAlpha(clrre));
```
Default resize (x2, crop center):  
![x2](https://i114.fastpic.ru/big/2021/0314/9c/043f9720dec292b53be781334307d79c.png)  
Enable RIS (x2, crop center):  
![x2-RIS](https://i114.fastpic.ru/big/2021/0314/76/0e8271453b85da81ae4534272d82f476.png)  

PS: In my opinion, Alpha will climb to the red channel.
