### ISSUE TITLE
CBZ and ZIP?

### ISSUE THREAD

**Issue by zvezdochiot** [ImageProcessing-ElectronicPublications/photoquick#28]
Hi @ksharindam .

⚠️ The question is just for consideration! This is not a problem! 

I keep all photos in CBZ with text description. To store photos as separate pictures is complete nonsense for me. 

I understand that CBZ (ZIP) support is an additional dependency, but it's worth considering at this point.

**Comment by ksharindam** [comment]
CBZ files are meant to be open in a ebook viewer.
So it is very unlikely that an image viewer will open CBZ format.

**Comment by zvezdochiot** [comment]
Overdue.
