### ISSUE TITLE
Effects: Color: Selective Bimodal Threshold (bimod)?

### ISSUE THREAD

**Issue by zvezdochiot** [ImageProcessing-ElectronicPublications/photoquick#3]
Hi @ksharindam  and all.

:question: Maybe add "Effects: Color: Selective Bimodal Thresold (bimod)"?

See https://github.com/ImageProcessing-ElectronicPublications/gimp-plugin-colors-bimod .

**Comment by ksharindam** [comment]
It can not be called a threshold.
Is not it something like Kuwahara Filter?

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

:information_source: No. Is this not a Kuwahara filter. If you are talking about example, then these are (5-1)=4 uniform thresholds with color separation (R, G, B) (channels) and averaging brightness (gray). For 2 and disabled options you will get a standard bimodal threshold. And the threshold will be applied to the selection!

:link: See https://github.com/ImageProcessing-ElectronicPublications/gimp-plugin-colors-bimod/blob/4a5d067655b50cff5938c9ce3e93ff9716ea8c40/colors_bimod.py#L20-L44 or https://github.com/ImageProcessing-ElectronicPublications/imthreshold/blob/64bbd4e5ab707b22a9b99d2ccd93ed27f769fcd9/src/lib/threshold.c#L33-L80

:warning: The lack of a frame of choice in "Effects: Color" is bad!

**Comment by ksharindam** [comment]
I have implemented this in my own repo. But could not merge with this repo.
Try to merge.

**Comment by zvezdochiot** [comment]
:heavy_check_mark: https://github.com/ImageProcessing-ElectronicPublications/photoquick/commit/2977e1ee6dfa408e70def2306fcf2a448e1ce8e3
