### ISSUE TITLE
Load Mask as "Shadow"?

### ISSUE THREAD

**Issue by zvezdochiot** [ImageProcessing-ElectronicPublications/photoquick#30]
Hi @ksharindam .

It doesn't fit well with the name, but some things (like blurring the background) can be done effectively with bw masks. Is it possible to implement in photoquick loading of masks, like "Shadow", so that resize and other deformation filters automatically occur if necessary?

**Comment by ksharindam** [comment]
Blurring the background (or any desired object) requires masking. 
But why resize and deformation requires masking?
I am thinking about adding a "Use as mask" button in scissor tool.

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

Not. This means that the mask should be scaled or warped along with the main image.

**Comment by zvezdochiot** [comment]
Overdue.
