### ISSUE TITLE
Localization? 

### ISSUE THREAD

**Issue by zvezdochiot** [ImageProcessing-ElectronicPublications/photoquick#31]
Hi @ksharindam .

Only question. I myself have no idea how localization files work in Qt. And most likely I will not understand. If this is a time consuming topic, you should close the issue right away.

**Comment by ksharindam** [comment]
I know nothing about localization. 
Never used or worked with localization in Qt or Gtk.

**Comment by zvezdochiot** [comment]
Ok. Close? Or let it hang?

**Comment by ksharindam** [comment]
Close it.

**Comment by zvezdochiot** [comment]
Ok.
