### ISSUE TITLE
Split Resize?

### ISSUE THREAD

**Issue by zvezdochiot** [ImageProcessing-ElectronicPublications/photoquick#33]
Hi @ksharindam .

Maybe split Resize into Fast and Advance? The first is simple, economical from memory. The second one includes all the features (RIS, steps, BiCubic). 

PS: I myself will not sculpt a new menu without asking.

**Comment by ksharindam** [comment]
Yes, advanced resize must be kept isolated from simple resize.
The resize button should open simple resize dialog.
Advanced resize should be inside Transform menu.

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

I found a way to split resize into light and heavy forms without additional dialogs. I think the question is closed. If not, open again.
