### ISSUE TITLE
Synchronization? 

### ISSUE THREAD

**Issue by zvezdochiot** [ImageProcessing-ElectronicPublications/photoquick#34]
![diff](https://i114.fastpic.ru/big/2021/0605/dc/b2bba2baf2d2abdebfa906afc0c431dc.png)

I can clone your repo by making all the differences in the code with the last summary commit. This will result in the loss of own story and comments, but will return the ability to compare differences normally.

How do you like this proposal?

**Comment by ksharindam** [comment]
I like the idea, because the thing "50 commits ahead, 26 commits behind" is irritating me also.
But I am thinking if the same thing may happen again ?

**Comment by zvezdochiot** [comment]
OK. Let it repeat itself. Nothing prevents me from repeating. 

Don't change anything for 1 hour. I am doing a shenanigans.

**Comment by ksharindam** [comment]
Dont do this today.
I have not commited the last change (move icons to data/) in my repo

**Comment by ksharindam** [comment]
I am working on creating AppImage. It may take one or two days to commit the last change.

**Comment by zvezdochiot** [comment]
Ok. I noticed. I'll wait.
 
PS: Add a message when ready.

**Comment by ksharindam** [comment]
Ok.
One more thing, I want to use that 96px photoquick icon for desktop icon (instead of 32px).
Because in desktop (both windows and linux) the 32px is scaled and becomes little hazy.

**Comment by zvezdochiot** [comment]
Although what to pull. I'll do a trial sync now, no tags sync. And after a couple of days, full.

**Comment by zvezdochiot** [comment]
✔️ ![sync](https://i114.fastpic.ru/big/2021/0605/3e/ffe3b8962dd9e13fce0f7b9ceeee1a3e.png)

Now you can compare.

**Comment by zvezdochiot** [comment]
@ksharindam .

⚠️ If you are working on the code of the current repo, rename it, clone it anew and replace the code with the one you are working with. (git history changed: `.git` directory)

PS: ℹ️ On your repo, apply: 
```sh
sed -i -e 's/\t/    /g' *.cpp *.h
```

**Comment by zvezdochiot** [comment]
@ksharindam .

Is GPL-3.0 really important to you? Or is the question of changing to PDM-1.0 (https://github.com/ImageProcessing-ElectronicPublications/python-pdf-jpeg-extract/blob/master/LICENSE) appropriate?

**Comment by ksharindam** [comment]
Yes, i like to keep it GPL licenced.

**Comment by zvezdochiot** [comment]
👍 Ok. No comment.

**Comment by zvezdochiot** [comment]
@ksharindam .

It is necessary to bring the documentation to the original. Don't spare commits. I will still do sync after fine-tuning.

And PS: ℹ️ On your repo, apply:
```sh
sed -i -e 's/\t/    /g' *.cpp *.h
```

**Comment by ksharindam** [comment]
You have done sync, now what to do ?

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

Synchronization is rather poor, most of the differences are related to tabs. You not did: 
```sh
sed -i -e 's/\t/    /g' *.cpp *.h
```
Because of this, significant differences are difficult to see.

**Comment by zvezdochiot** [comment]
@ksharindam .

Now all the differences are visible. At this stage, that's enough. Then you can repeat.
