### ISSUE TITLE
Gray option in bimodal threshold is confusing

### ISSUE THREAD

**Issue by ksharindam** [ImageProcessing-ElectronicPublications/photoquick#4]
the checkbox text should be changed from gray to something like "Histogram Based".
Else user will think that it will output grayscale image if checkbox is checked.

**Comment by zvezdochiot** [comment]
:question: Gray --> Brightness? BaseLevel? Brightness Correct?

**Comment by zvezdochiot** [comment]
:question: Maybe there are 2 options ?:
* Brightness --> Average between thresholds
* Gray --> (R, G, B) -> (A, A, A), A = (R + G + B) / 3

**Comment by zvezdochiot** [comment]
:question: Maybe you should transfer Bimodal to Effects->Color?

**Comment by ksharindam** [comment]
when gray is not checked it produces simple multilevel threshold. but when it is checked it produces colors **closer to the original** using the histogram.
This has no relation to brightness so Brightness word would be improper.
Also it does not produce average of R,G, and B . so "Average" word is also improper.

**Comment by ksharindam** [comment]
I will move it under color menu

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

:information_source: You send commits to this fork. And you always have time to send PR to yourself.

>improper

:question: Maybe "Median"?

**Comment by ksharindam** [comment]
Median is acceptable
