### ISSUE TITLE
ReOpen?

### ISSUE THREAD

**Issue by zvezdochiot** [ImageProcessing-ElectronicPublications/photoquick#6]
:question: Maybe add "ReLoad" current image?

**Comment by ksharindam** [comment]
As it is a quick opening image viewer.
One can just close window and double click to reopen image.
But if you want to undo changes, an undo option can be added.

**Comment by ksharindam** [comment]
Most of the image viewers dont require reload button.

**Comment by zvezdochiot** [comment]
@ksharindam say:
>an undo option can be added.

:warning: Too much trouble and hardly a good result. ReOpen is simpler and more reliable.

**Comment by ksharindam** [comment]
what about adding a keyboard shortcut, such as press "R" to reload?

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

This is a pretty good idea.

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

:warning: Reload not work of " default image".

But this is not critical at all.

**Comment by ksharindam** [comment]
Yes, the default image is just for demo. nobody will work with the default image.
