### ISSUE TITLE
Clean Range?

### ISSUE THREAD

**Issue by zvezdochiot** [ImageProcessing-ElectronicPublications/photoquick#7]
:question: Maybe add "Clean" with indicating background color in group "Crop"?

**Comment by zvezdochiot** [comment]
:question: Or use "Bimod" for "Clean mask" and "BG mask" -> "BG color" (average).

**Comment by ksharindam** [comment]
I did not understand what do you want to do. Please elaborate

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

I’ll try to clarify:

![lena.png](https://i112.fastpic.ru/big/2020/0619/bd/42734b84ef358089d443fc23722984bd.png)

Scheme 1 (simple):

![scheme 1](https://i112.fastpic.ru/big/2020/0619/05/f3ee17faec71db1cd78fea4674e36105.png)

Scheme 2 (with mask):

![clean mask](https://i112.fastpic.ru/big/2020/0619/2a/69c97e633bd886e0dd1ff2ade221182a.png)

![scheme 2](https://i112.fastpic.ru/big/2020/0619/e8/2f4c8bef9fadf53c3a25cd89dce450e8.png)

**Comment by zvezdochiot** [comment]
See https://github.com/ImageProcessing-ElectronicPublications/photoquick/issues/9
