### ISSUE TITLE
Build instruction?

### ISSUE THREAD

**Issue by zvezdochiot** [ImageProcessing-ElectronicPublications/photoquick#8]
:question: Maybe change?:

---  
To build this program, extract the source code zip.  
Open terminal and change directory to src/  
Then run these commands to compile...  
```sh
qmake  
make -j4  
```
---  

To:

---  
To build this program, extract the source code zip.  
Then run these commands to compile...  
```sh
qmake src
make -j4  
```
---

**Comment by ksharindam** [comment]
that looks cleaner

**Comment by zvezdochiot** [comment]
Rather not cleaner, but easier.

**Comment by zvezdochiot** [comment]
https://github.com/ImageProcessing-ElectronicPublications/photoquick/commit/45a4640a0ebff945f69694375af5ed8c0e902d4f
